[project]
name = "selfbot"
version = "2026.02.12"
description = "Telegram Selfbot"
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "asyncpg==0.31.0",
    "httpx[http2]==0.28.1",
    "py-tgcalls==2.2.11",
    "pyrotgfork==2.2.21",
    "pytgcrypto==1.2.12",
    "telegraph[aio]==2.2.0",
]

[project.scripts]
selfbot = "selfbot.main:run"

[tool.uv]
package = true
