name: Push

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build - Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REPO }}:${{ github.ref_name }}
